USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make
TITLE=enable_firmware_password
PACKAGE_VERSION=1.0
REVERSE_DOMAIN=org.domain
PAYLOAD=\
	pack-script-postinstall\
	pack-usr-sbin-setregproptool
